### ISSUE TITLE
Student - Add Student - Change "Category of the Caste(SC/ST/BC/OC)" field to dropdown 

### ISSUE THREAD

**Issue by phanipavan** [WasimSutar/VJHS#11]
Change the field **"Category of the Caste(SC/ST/BC/OC)"** to dropdown with the below options

OC
BC - A
BC - B
BC - C
BC - D
SC
ST
Others

**Comment by GangadharReddy** [comment]
Resolved. Test and confirm.
![coc](https://cloud.githubusercontent.com/assets/8049229/22396296/1b997a6e-e57b-11e6-988d-f3e0e9b11e14.png)

**Comment by phanipavan** [comment]
Can see the dropdown and working fine.
