### ISSUE TITLE
Student - Add Student - Discrepancy in TC fields

### ISSUE THREAD

**Issue by phanipavan** [WasimSutar/VJHS#12]
Even though "Whether record sheet/ T.C is produced, if yes its number and date" field is selected as "No"
the fields "Enter Transfer Certificate Number" and "TC Date" are appearing.
![tc issue](https://cloud.githubusercontent.com/assets/15225327/20935401/8f6b40a8-bc04-11e6-9ee8-215213ebc615.JPG)

**Comment by GangadharReddy** [comment]
Resolved. Test and confirm.

**Comment by phanipavan** [comment]
Working fine
