### ISSUE TITLE
Student - Add Student - Date fields are accepting future dates

### ISSUE THREAD

**Issue by phanipavan** [WasimSutar/VJHS#7]
DOB and DOJ fields are accepting future date 
![add_stu_date](https://cloud.githubusercontent.com/assets/15225327/20934729/2a8cb45c-bc02-11e6-8031-42755e87911f.jpg)

**Comment by GangadharReddy** [comment]
Fixed. Test and confirm

**Comment by phanipavan** [comment]
Working fine
